# Generated by Django 3.1.1 on 2021-04-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210402_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
