# Generated by Django 3.1.1 on 2021-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210323_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('applyfor', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('emailid', models.EmailField(max_length=254)),
                ('resume', models.FileField(upload_to='cvs/%Y/%m/%d/')),
            ],
        ),
    ]
