# Generated by Django 3.1.1 on 2021-04-07 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_by', models.CharField(max_length=50)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_article', models.TextField()),
                ('blog_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
