# Generated by Django 3.1.1 on 2021-04-08 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_blog_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_by',
            new_name='by',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_thumbnail',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
    ]
