# Generated by Django 3.1.1 on 2021-04-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210407_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subheading',
            field=models.CharField(default='this is default subheading. ', max_length=100),
            preserve_default=False,
        ),
    ]
